version: '3.8'

services:
  app:
    build:
      context: ../..
      dockerfile: docker/dev/Dockerfile.dev
    image: next-blog-app:dev
    container_name: next-blog-app-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ../..:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]
