version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    volumes:
      - ./.next/standalone:/app
      - ./.next/static:/app/.next/static
      - ./public:/app/public
    command: ["node", "server.js"]
