version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    image: next-blog-app:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    command: ["node", "server.js"]
